# Generated by Django 3.1.1 on 2020-10-30 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_orderupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderupdate',
            old_name='time_stamp',
            new_name='timestamp',
        ),
    ]
